name: tmdb
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=2.16.1 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.6.1
  flutter:
    sdk: flutter
  dio: ^4.0.4
  google_fonts: ^2.3.1
  flutter_rating_bar: ^4.0.0
  carousel_slider: ^4.0.0
  cached_network_image: ^3.2.0
  url_launcher: ^6.0.20
  equatable: ^2.0.3
  flutter_svg: ^1.0.3
  internet_connection_checker: ^0.0.1+3
  lottie: ^1.2.2

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true


  assets:
    - assets/images/
    - assets/icons/
    - lottie/


